export const RESPONSIVE_DRAWER_TOGGLE_DRAWER_OPEN = 'RESPONSIVE_DRAWER_TOGGLE_DRAWER_OPEN';
export const RESPONSIVE_DRAWER_TOGGLE_DRAWER_DOCK = 'RESPONSIVE_DRAWER_TOGGLE_DRAWER_DOCK';
export const RESPONSIVE_DRAWER_SET_DRAWER_OPEN = 'RESPONSIVE_DRAWER_SET_DRAWER_OPEN';
export const RESPONSIVE_DRAWER_SET_RESPONSIVE = 'RESPONSIVE_DRAWER_SET_RESPONSIVE';

export const LOAD_CHAPTERS_SUCCESS = 'LOAD_CHAPTERS_SUCCESS';
export const CREATE_CHAPTER_SUCCESS = 'CREATE_CHAPTER_SUCCESS';
export const UPDATE_CHAPTER_SUCCESS = 'UPDATE_CHAPTER_SUCCESS';
export const REMOVE_CHAPTER_SUCCESS = 'REMOVE_CHAPTER_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS';
export const LOAD_LESSON_SUCCESS = 'LOAD_LESSON_SUCCESS';
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS';
export const REMOVE_LESSON_SUCCESS = 'REMOVE_LESSON_SUCCESS';



export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';

